# name: Deployment
# on:
#   push:
#     branches:
#       - master
# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         node-version: [12.x]
#     steps:
#     - uses: actions/checkout@v1
#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v1
#       with:
#         node-version: ${{ matrix.node-version }}
#     - name: Install Packages
#       run: npm install
#     - name: Build page
#       run: npm run build
#     - name: Deploy to gh-pages
#       uses: peaceiris/actions-gh-pages@v3
#       with:
#         deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
#         publish_dir: ./build

name: Deploy to gh-pages

on:
  push:
    branches:
      - master

jobs:
  gh-pages-deploy:
    name: Deploying to gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v1.1.0
        with:
          version:  16.8
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      - name: Checkout branch
        uses: actions/checkout@v2
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

      - name: Clean install dependencies
        run: npm install
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

      - name: Build app
        run: npm run predeploy
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./build
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'